logging:
  level:
    root: info

server:
  port: 8807

management:
  health:
    elasticsearch:
      enabled: false

spring:
  application:
    name: bot

  redis:
    database: 2
    host: 192.168.50.103
    port: 6379
    password: G!Ps&eEwtsxd7NGf
    timeout: 5000

  data:
    jpa:
      repositories:
        enabled: true
    elasticsearch:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:postgresql://192.168.50.102:5432/postgres?currentSchema=bot
    username: postgres
    password: JpESiz1nHf
    pool:
      enabled: true

  elasticsearch:
    rest:
      uris: [ "http://192.168.50.104:9200" ]

  cloud:
    inetutils:
      ignored-interfaces:
        - eth*
      preferred-networks:
        - 192.168.*
    consul:
      host: 192.168.50.108
      port: 80
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
        # health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
    loadbalancer:
      ribbon:
        enabled: false

  security:
    oauth2:
      client:
        provider:
          authProvider:
            token-uri: http://oauth2-auth-server/oauth/token
        registration:
          authProvider:
            client-id: inner_client
            client-secret: test_secret
            authorization-grant-type: client_credentials
